#!/bin/sh
set -eu

# aifinpay installer — downloads the right binary from GitHub Releases and
# verifies it against the SHA256SUMS generated by scripts/build.sh.
# Usage: curl -fsSL https://raw.githubusercontent.com/AiFinPay/aifinpay-cli/main/install.sh | sh

REPO="AiFinPay/aifinpay-cli"
NAME="aifinpay"

detect_os() {
  case "$(uname -s | tr '[:upper:]' '[:lower:]')" in
    linux*)  echo "linux" ;;
    darwin*) echo "darwin" ;;
    mingw*|msys*|cygwin*) echo "windows" ;;
    *) echo "unsupported" ;;
  esac
}
detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *) echo "unsupported" ;;
  esac
}

download() {
  src="$1"; dst="$2"
  if command -v curl >/dev/null 2>&1; then curl -fsSL "$src" -o "$dst"
  elif command -v wget >/dev/null 2>&1; then wget -qO "$dst" "$src"
  else echo "Error: need curl or wget" >&2; exit 1; fi
}

sha256_file() {
  file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{print $1}'
  else
    echo "Error: need sha256sum or shasum to verify release integrity" >&2
    exit 1
  fi
}

OS=$(detect_os); ARCH=$(detect_arch)
if [ "$OS" = "unsupported" ] || [ "$ARCH" = "unsupported" ]; then
  echo "Error: unsupported platform $(uname -s)/$(uname -m)" >&2; exit 1
fi

EXT=""; [ "$OS" = "windows" ] && EXT=".exe"
ASSET="${NAME}-${OS}-${ARCH}${EXT}"
BASE="https://github.com/${REPO}/releases/latest/download"
URL="${BASE}/${ASSET}"
SUMS_URL="${BASE}/SHA256SUMS"

if [ -w "/usr/local/bin" ] 2>/dev/null; then DEST="/usr/local/bin"
elif [ -n "${HOME:-}" ]; then DEST="${HOME}/.local/bin"; mkdir -p "$DEST"
else DEST="."; fi

echo "Downloading ${ASSET}"
TMP="$(mktemp)"
SUMS="$(mktemp)"
cleanup() { rm -f "$TMP" "$SUMS"; }
trap cleanup EXIT HUP INT TERM

download "$URL" "$TMP"
download "$SUMS_URL" "$SUMS"

EXPECTED=$(awk -v asset="$ASSET" '$2 == asset || $2 == "*" asset { print $1; exit }' "$SUMS")
if [ -z "$EXPECTED" ]; then
  echo "Error: ${ASSET} is not present in release SHA256SUMS" >&2
  exit 1
fi
ACTUAL=$(sha256_file "$TMP")
if [ "$ACTUAL" != "$EXPECTED" ]; then
  echo "Error: SHA-256 mismatch for ${ASSET}" >&2
  echo "  expected: ${EXPECTED}" >&2
  echo "  actual:   ${ACTUAL}" >&2
  exit 1
fi

echo "SHA-256 verified: ${ACTUAL}"
chmod +x "$TMP"
mv "$TMP" "${DEST}/${NAME}${EXT}"
trap - EXIT HUP INT TERM
rm -f "$SUMS"

echo "Installed ${NAME} to ${DEST}/${NAME}${EXT}"
case ":${PATH}:" in
  *":${DEST}:"*) : ;;
  *) echo "Note: ${DEST} is not on your PATH — add it: export PATH=\"${DEST}:\$PATH\"" >&2 ;;
esac
echo "Requires Node.js on the host. Run: ${NAME} --help"
